Add Job pacemaker
valohai/minique pull request #19
Opened 2021-09-15 07:55 UTC by tokkoro

Add heartbeat into a job's Redis Hash. Minique Worker will update a heartbeat of its' job every 60 seconds.

The idea is that other systems can listen to this heartbeat and determinate if it has been too long and something bad has to happen to the job.

2021-09-15 08:02 UTC, akx requested changes
The heartbeat API should be in the job model, as it is implemented here. That's fine. (Could use a docst

However, actually beating the heart and the implementation to do so must not be forced by Minique itself. For instance, in our proposed use case a background thread that doesn't know about how the task itself is executing is not a very good heartbeat.

So please move the "example implementation" over to the tests for this feature (which don't yet exist) :)

2021-09-15 08:02 UTC, akx commented on minique/work/worker.py
> +        heart.join()
Re the earlier comment about moving the thread implementation to tests, this would also be snipped out.

```suggestion
```

2021-09-15 08:02 UTC, akx commented on minique/work/worker.py
> +    heart_rate = 60
```suggestion
```

2021-09-15 08:02 UTC, akx commented on minique/models/job.py
> +    def heartbeat(self) -> Optional[float]:
Docstring, if you would?

2021-09-15 08:02 UTC, akx commented on minique/models/job.py
> +    def refresh_heartbeat(self):
Docstring, if you would?

2021-09-15 08:21 UTC, tokkoro commented on minique/models/job.py
> +    def heartbeat(self) -> Optional[float]:
cannot resolve

2021-09-17 09:02 UTC, akx approved these changes

2021-09-17 09:03 UTC, merged